### ISSUE TITLE
Setup Query

### ISSUE THREAD

**Issue by steveabraham** [gregpechiro/playerMarkers#1]
Hello,

Thanks for building this! I'm probably being really stupid here, but struggling a bit with the set up, wondering if you can guide me.

I'm working on a Debian server where the Minecraft server is running as well as the MapCrafter setup.

I've done the following:

- Downloaded the repo onto a folder
- Modified player-markers-tmpl.js 
- Made a config.json from the my-config.json file

But I can't figure out the next step about running the 'playerMarkers' command... I'm not sure what I'm running.

Thanks!

**Comment by xiphoid24** [comment]
So what you cloned is the source code. I didn't pre-compile it. I can compile it for you. Are you running 64-bit?

**Comment by steveabraham** [comment]
Aha!
Yes, 64-bit Debian 9.1. I'm happy to attempt a compile if you can let me know what I need to do - thank you!

**Comment by xiphoid24** [comment]
You will need golang installed. First download [Go](https://golang.org/dl/), Next follow the [installation guide](https://golang.org/doc/install). After that you can move the repo to your $GOPATH/src. cd  into the repo and run `go install`. Let me know if you need any more help!

**Comment by steveabraham** [comment]
Working! Thanks so much for your help, this is brilliant.

One (last!) question. With Overviewer I have the player markers only show for players active in the last 15 minutes, is there any way to do that with this?

**Comment by xiphoid24** [comment]
Not sure I'll into it. Usually when I develop I just build what I need which is why it't not currently supported. I will look into to it and message you asap.

**Comment by steveabraham** [comment]
No problem, it would be great if that was possible. It means it comes very close to being a 'live' map, which is how we've been using it with Overviewer up till now on a Vanilla server.

**Comment by xiphoid24** [comment]
I updated the repo. I added a ModTime to the user. It is the same way Overviewer does it which it just the last mod time of the file. You can add template logic to the player-marker.js.tmpl to check the mod time and exclude certain players. Let me know how this works. I didn't get to test it too thoroughly. You  will need to `git pull` the repo then recompile.

Example
 ```
{{ range $user := . }}
{{ if ne $user.Dimension 1 }}
{{ if lt $user.ModTime 900 }} // added line
    {
        "pos" : [{{ $user.X }}, {{ $user.Z }}, {{ $user.Y }}],
        "title" :"{{ $user.Username }}",
        "text" : '<div style="text-align: center;">{{ $user.Username }}</div><br><b>Location:</b> X: {{ $user.X }}, Y: {{ $user.Y }}, Z: {{ $user.Z }}',
        "icon" : "{{ $user.Uuid }}.png",
    },
{{ end }} // added line
{{ end }}
{{ end }}
```
This checks to see if the user ModTime is less than 15 mins.

**Comment by steveabraham** [comment]
That's amazing, I'll give it a try and let you know how I get on. Thanks so much for doing that!

**Comment by steveabraham** [comment]
So I've downloaded and recompiled, and this what's happening:

I wasn't getting any player markers showing until I removed the "{{ if lt $user.ModTime 900 }}" conditional. Then they all showed up again. I added "{{ $user.ModTime }}" to the text output and I'm getting values like "1504043890" in the text bubble.

So I assume it's just a conditional issue, unless I've missed something?

Test map for reference: http://map.spodcraft.com/mapcrafter/

**Comment by xiphoid24** [comment]
I'm sorry about that. I realized as I was driving that was wrong. I'll put out a patch as soon as I can. Probably something like `$user.DifTime` will be now minus the mod time.

**Comment by steveabraham** [comment]
No problem! Thanks for doing all this, it's awesome!

**Comment by xiphoid24** [comment]
Ok I have updated the time. There is a mod time on the user which is the date the file was last modified in a unix time stamp. There is also a DifTime on a user. This is the different between now (unix time stamp) and the mod time. All are  in seconds. There are some other things I would like to do to improve this but it should work for now.

Example
 ```
{{ range $user := . }}
{{ if ne $user.Dimension 1 }}
{{ if lt $user.DifTime 900 }} // added line
    {
        "pos" : [{{ $user.X }}, {{ $user.Z }}, {{ $user.Y }}],
        "title" :"{{ $user.Username }}",
        "text" : '<div style="text-align: center;">{{ $user.Username }}</div><br><b>Location:</b> X: {{ $user.X }}, Y: {{ $user.Y }}, Z: {{ $user.Z }}',
        "icon" : "{{ $user.Uuid }}.png",
    },
{{ end }} // added line
{{ end }}
{{ end }}
```

**Comment by xiphoid24** [comment]
If this works can we close the issue? Also if possible could you email me. I would like some perspective on how you use this so I can improve it and I don't want to take up space in the issues section.

**Comment by steveabraham** [comment]
Just sent you an email, please feel free to close this off. :)
